ALTER TABLE "PlayerStats" ADD COLUMN "foulsDrawn" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "WorldCupStats" ADD COLUMN "foulsDrawn" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "WorldCupMatchStats" ADD COLUMN "foulsDrawn" INTEGER NOT NULL DEFAULT 0;
